- name: remediate_memory_process
  hosts: all
  tasks:

   - name: connect
     shell: |
           sleep 400
     register: os_info
     ignore_errors: true
     delegate_to: localhost
    
     
      
   - debug:
        msg: "{{os_info.stdout_lines}}"
