- name: remediate_stress_process
  hosts: localhost
  tasks:

   - name: connect
     shell: |
           for pid in $(ps -ef | grep "stress-ng" | awk '{print $2}'); do sudo kill -9 $pid; done 
           echo {{result}}
     register: os_info
     ignore_errors: true
     delegate_to: localhost
    
     
      
   - debug:
        msg: "{{os_info.stdout_lines}}"
