- name: remediate_stress_process
  hosts: "{{ip}}"
  tasks:
   - name: try become method sudo
     command: whoami
     register: who
     ignore_errors: True

   - name: killstress
     command: for pid in $(ps -ef | grep "stress-ng" | awk '{print $2}'); do kill -9 $pid; done 
     register: stdd
     ignore_errors: false


   - debug: msg="{{ who.stdout }}"
   - debug: msg="{{ who.stderr }}"
   - debug: msg="{{ stdd.stdout }}"
   - debug: msg="{{ stdd.stderr }}"
