- name: remediate_stress_process
  hosts: "{{ip}}"
  tasks:

   - name: killstress
     ansible.builtin.ssh connection: ps -ef
     register: stdd
     ignore_errors: false


   - debug: msg="{{ stdd.stdout }}"
   - debug: msg="{{ stdd.stderr }}"
