- name: remediate_stress_process
  hosts: "{{ip}}"
  connection: ssh
  tasks:

   - name: killstress
     shell: |
            ls -la
            sleep 60
     register: stdd
     ignore_errors: true


   - debug: msg="{{ stdd.stdout }}"
   - debug: msg="{{ stdd.stderr }}"
