- name: remediate_stress_process
  hosts: "{{ip}}"
  connection: ssh
  tasks:

   - name: killstress
     shell: |
          sudo pkill stress-ng || true
     register: stdd
     ignore_errors: true


   - debug: msg="{{ stdd.stdout }}"
   - debug: msg="{{ stdd.stderr }}"
