- name: remediate_stress_process
  hosts: "{{ip}}"

   - name: killstress
     command: ps -ef | grep "stress-ng" 
     register: stdd
     ignore_errors: false


   - debug: msg="{{ stdd.stdout }}"
   - debug: msg="{{ stdd.stderr }}"
