- name: remediate_stress_process
  hosts: "{{ip}}"
  connection: ssh
  tasks:

   - name: killstress
     win_shell: |
            echo "hello"
     register: stdd
     ignore_errors: true


   - debug: msg="{{ stdd.stdout }}"
   - debug: msg="{{ stdd.stderr }}"
