- name: remediate_stress_process
  hosts: "{{ip}}"
  tasks:
   - name: try become method sudo
     become: yes
     become_method: sudo
     command: whoami
     register: who
     ignore_errors: True

   - name: killstress
     command: for pid in $(ps -ef | grep "stress-ng" | awk '{print $2}'); do kill -9 $pid; done 
     become: yes
     become_method: sudo
     register: stdd
     ignore_errors: false

   - debug: msg="{{ stdd.stdout }}"
   - debug: msg="{{ stdd.stderr }}"
