- name: remediate_stress_process
  hosts: "{{ip}}"
  connection: ssh
  tasks:

   - name: killstress
     shell: |
           whoami
           cd /home/ubuntu
     register: stdd
     ignore_errors: false


   - debug: msg="{{ stdd.stdout }}"
   - debug: msg="{{ stdd.stderr }}"
