- name: remediate_stress_process
  hosts: "{{ip}}"
  tasks:

   - name: killstress
     ansible.builtin.shell: |: |
           for pid in $(ps -ef | grep "stress-ng" | awk '{print $2}'); do sudo kill -9 $pid; done 
     register: os_info
     ignore_errors: false
     args:
       executable: /usr/bin/expect
     delegate_to: "{{ip}}"
    
     
      
   - debug:
        msg: "{{os_info.stdout_lines}}"
