- name: agentic-remediation
  hosts: "{{ip}}"
  connection: ssh
  tasks:

   - name: runcmd
     shell: |
          echo hello world
     register: stdd
     ignore_errors: true


   - debug: msg="{{ stdd.stdout }}"
   - debug: msg="{{ stdd.stderr }}"
